### PR TITLE
Add GIF event support and improve unit test framework

### PR DESCRIPTION
**Pull request by ammarfaizi2**
1. Add GIF event support by @ALiwoto.
2. Improve unit test framework.
3. Update GitHub workflows.
4. Add clang build and test for GitHub action.
---
```
	Signed-off-by: Aliwoto <aminnimaj@gmail.com>
	Signed-off-by: Ammar Faizi <ammarfaizi2@gmail.com>
```

### CODE REVIEW

**Comment by ammarfaizi2** [comment]
@nrudesu @ALiwoto I need approval to merge this into master branch.

**Review by ALiwoto — DISMISSED** [review]
Nice!
Everything is okay, and I don't see any problem at all.
Also your unit test framework is amazing Ammar!

**Comment by ammarfaizi2** [comment]
Hi, sorry for the late commit, as I pushed a change, it dismissed the approval from @ALiwoto. I request a re-approval from @ALiwoto. Also I need approval from @nrudesu too.

The master branch is strictly protected so that the PR can only be merged when there are at least *two reviewers* who approve the changes.

Thank you.

**Review by ALiwoto — APPROVED** [review]
very well.

**Review by nrudesu — APPROVED** [review]

**Comment by ammarfaizi2** [comment]
Merged, thanks.

**Pull request merged**
